name: sort_strings
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/AkmaljonAbdirakhimov/sort_strings
homepage: https://github.com/AkmaljonAbdirakhimov/sort_strings

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
